### ISSUE TITLE
lite-xl now is out of date

### ISSUE THREAD

**Issue by tan-wei** [prantlf/homebrew-tap#2]
v2.1.1 is not available and v2.1.4 is released.

Ref:
  - https://github.com/lite-xl/lite-xl/releases/tag/v2.1.4

**Comment by prantlf** [comment]
Thanks for reporting this! I've just fixed it and enabled a semi-automated update like for other packages in this tap.

**Comment by prantlf** [comment]
It appears that the symlink `lite` created in the appdir doesn't work any more. The code in the binary detects the application directory to load the some assets from it. It doesn't resolve symlinks, if the binary is executed via one:

    Error: cannot open /usr/local/bin/core/start.lua: No such file or directory
    stack traceback:
      [C]: in function 'dofile'
      [string "local core..."]:11: in function <[string "local core..."]:6>
      [C]: in function 'xpcall'
      [string "local core..."]:6: in main chunk

I'll try to look at it later. For the time being, you can create a shell alias instead. You may just execute the following command, or include it in .bashrc or .zshrc:

    alias lite='"/Applications/Lite XL.app/Contents/MacOS/lite-xl"'

I let it printed as a caveat during the installation of this package too.

**Comment by tan-wei** [comment]
Great, thanks for your quick reply.
